### ISSUE TITLE
Add an SPI controller for reading

### ISSUE THREAD

**Issue by nmigen-issue-migration** [amaranth-lang/amaranth-stdio#2]
<a href="https://github.com/HarryHo90sHK"><img src="https://avatars3.githubusercontent.com/u/6345728?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [HarryHo90sHK](https://github.com/HarryHo90sHK)**
_Monday Dec 23, 2019 at 08:38 GMT_
_Originally opened as https://github.com/m-labs/nmigen-stdio/pull/2_

----

On this pull request, I propose an SPI flash controller module exclusively for reading data or registers out of a flash device. Currently, it has: 

* `_SPIFlashReaderBase`: a base class from which can be inherited to create a new controller module, such as one that reads the ID of the flash device by issuing the opcode `0x9F` (or `0x9E`)
* `SPIFlashSlowReader`: a module for normal reads from the device, meaning no dummy cycles of waiting is needed right after sending the address bytes to the device, while the read frequency is often capped. 
* `SPIFlashFastReader`: a module for "fast reads", meaning a faster frequency than normal reads while a number of dummy cycles of waiting is needed right after sending the address bytes.

Note that only the `SlowReader` but not the `FastReader` has been successfully tested on the ECP5 evaluation board.

In order to use the clock signal `clk` as the SPI clock for this module design, ECP5 requires the user **NOT** to request for SPI clock that corresponds to the on-chip oscillator (MCLK) but to instantiate a USRMCLK Instance. Therefore, to use this module and bulid the configuration bitstream on nextpnr without errors (see [this comment](https://github.com/YosysHQ/nextpnr/issues/290#issuecomment-536397715)), the user must avoid requesting for the normal clock pin from Ball U3 by some means. One way is to use my [proposed modification of nmigen-boards](https://github.com/m-labs/nmigen-boards/pull/38).

I look forward to seeing further comments, thanks.

----

_**[HarryHo90sHK](https://github.com/HarryHo90sHK)** included the following code: https://github.com/m-labs/nmigen-stdio/pull/2/commits_

**Comment by whitequark** [comment]
The PR is outdated and the author is no longer working on it.
